In this notebook we will find the inverse of a matrix and multiply two matrices. *NOTE: It is important to keep in mind that when multiplying two matrices the number of columns of the first matrix needs to be equal to the number of rows of the second matrix. For example, if A is a $1\times 3$ matrix and B is a $3 \times 4$ matrix we can find A times B but not B times A.

In [1]:
import numpy as np
  
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print('A = ')
print(A)  
# Calculating the inverse of the matrix
print('The inverse of matrix A =')
B = np.linalg.inv(A)
print(B)

A = 
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
The inverse of matrix A =
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [2]:
C = np.array([[3,4,5],[6,7,8]])
print('C = ')
print(C)
D = np.array([[1,2,3,0], [9,8,7,-1], [-1,0,2,3]])
print('D = ')
print(D)
Product = np.dot(C,D)
print('The product of matrix C and matrix D is ')
print(Product)

C = 
[[3 4 5]
 [6 7 8]]
D = 
[[ 1  2  3  0]
 [ 9  8  7 -1]
 [-1  0  2  3]]
The product of matrix C and matrix D is 
[[34 38 47 11]
 [61 68 83 17]]
